### ISSUE TITLE
Cannot read property 'isolatedPath' of undefined

### ISSUE THREAD

**Issue by sisPedro** [kentcdodds/advanced-react-hooks#104] opened 2020-11-18 21:28 UTC
I've been working with the advance-react-hooks for a couple of days. I went through the first 2 exercises with no problems. Today I did ``npm run`` which worked fine but after restarting my PC unintentionally I couldn't run it anymore. The error message is the following 

![image](https://user-images.githubusercontent.com/16280628/99589542-e3634b00-29ca-11eb-924c-a12c1475d43e.png)

![console](https://user-images.githubusercontent.com/16280628/99589274-85366800-29ca-11eb-8fb6-685d62853852.PNG)

![image](https://user-images.githubusercontent.com/16280628/99589241-7b146980-29ca-11eb-8104-faaf67d577c0.png)

this is my Package.json :
```
"engines": {
    "node": "^10.13 || 12 || 14 || 15",
    "npm": ">=6"
  },
  "dependencies": {
    "@kentcdodds/react-workshop-app": "^2.19.10",
    "@testing-library/react": "^11.1.2",
    "@testing-library/user-event": "^12.2.2",
    "chalk": "^4.1.0",
    "codegen.macro": "^4.0.0",
    "mq-polyfill": "^1.1.8",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-error-boundary": "^3.0.2"
  },
  "devDependencies": {
    "@types/react": "^16.9.56",
    "@types/react-dom": "^16.9.9",
    "husky": "^4.3.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.1.2",
    "react-scripts": "^4.0.0"
  },
```
It should be noted that when navigating to an exercise (localhost:3000/1) the page renders properly.
Let me know If there's anything else I can post here. Thanks

**Comment by kentcdodds** [comment] 2020-11-18 21:48
For anyone watching, I'd welcome additional analysis. Pedro and I have discussed this on discord and I am unable to reproduce this 😬

**Comment by JacobMGEvans** [comment] 2020-11-23 19:05
@sisPedro What is your operating system and where are you keeping the Repository locally?

**Comment by sisPedro** [comment] 2020-11-25 05:42
Hello @JacobMGEvans. Im using Windows 10 (current patch) and the route is 
``C:\Users\Pedro\Documents\React\EpicReact\advanced-react-hooks``

**Comment by BENOITHAVETlmj** [comment] 2020-12-10 16:07
i add the same issue.
solved with `rm -rf node_modules package-lock.json` and `npm install`

**Comment by JacobMGEvans** [comment] 2020-12-10 16:46
> Hello @JacobMGEvans. Im using Windows 10 (current patch) and the route is
> `C:\Users\Pedro\Documents\React\EpicReact\advanced-react-hooks`
> And I did try removing node_modules and reinstalling

WSL2 (Linux subsystem) or just Windows environment?

**Comment by sisPedro** [comment] 2020-12-17 15:15
I'm sorry for the delayed response. I'm using Windows enviroment. I deleted the project and the error went away. Been trying to reproduce it but didn't get much done. I noticed there were some strange permision configurations in some subfolders as I was deleting the project. Might have something to do. I'll let you know if I manage to reproduce it again.

**Comment by kentcdodds** [comment] 2021-01-08 13:49
I'll close this until it's reproduced. Thanks!

**Closed by kentcdodds** 2021-01-08 13:49 UTC

**Comment by xugetsu** [comment] 2021-05-05 20:03
> I'll close this until it's reproduced. Thanks!

I was able to reproduce: If you create any file with any name under 'src/final' or 'src/exercise' and restart the server you will get this error. (I wanted to create my custom ErrorBoundary component in its own file which caused this issue.)
and I'm using macOs btw so apparently it has nothing to do with your OS type.

**Comment by kentcdodds** [comment] 2021-05-06 05:54
Ah, that's not supported. You'd need to put it anywhere else in `src`. I'm not sure how to improve the error message here I'm afraid.
